/**
 * Centralized UI text. Organized by area: Buttons, Auth, Dashboard, Errors, Messages, Labels.
 */
export const Buttons = {
  LOGIN: 'Login',
  LOGIN_LOADING: 'Signing in...',
  SIGN_UP: 'Sign up',
  CREATE_ACCOUNT: 'Create account',
  CREATE_ACCOUNT_LOADING: 'Creating account...',
  SEND_RESET_LINK: 'Send reset link',
  SEND_RESET_LINK_LOADING: 'Sending...',
  RESET_PASSWORD: 'Reset password',
  RESET_PASSWORD_LOADING: 'Resetting...',
  GO_TO_LOGIN: 'Go to login',
  BACK_TO_LOGIN: 'Back to login',
  LOGOUT: 'Logout',
  LOG_OUT: 'Log Out',
  CHANGE_PASSWORD: 'Change Password',
  CHANGE_PASSWORD_AGAIN: 'Change Password Again',
  CHANGING_PASSWORD: 'Changing password...',
  REQUEST_NEW_RESET_LINK: 'Request a new reset link',
} as const;

export const Auth = {
  SIGN_IN_TITLE: 'Sign in to Refinery',
  ENTER_DETAILS_BELOW: 'Enter your details below',
  CREATE_ACCOUNT_TITLE: 'Create your account',
  FORGOT_PASSWORD_TITLE: 'Forgot password',
  FORGOT_PASSWORD_SUBTITLE: "Enter your email and we'll send you a reset link",
  RESET_PASSWORD_TITLE: 'Reset password',
  RESET_PASSWORD_SUBTITLE: 'Enter your new password below',
  REMEMBER_ME: 'Remember me',
  FORGOT_PASSWORD_LINK: 'Forgot password?',
  DONT_HAVE_ACCOUNT: "Don't have an account?",
  ALREADY_HAVE_ACCOUNT: 'Already have an account?',
  EMAIL_ADDRESS: 'Email address',
  PASSWORD: 'Password',
  FULL_NAME: 'Full name',
  CONFIRM_PASSWORD: 'Confirm password',
  NEW_PASSWORD: 'New password',
  CURRENT_PASSWORD: 'Current password',
  SHOW_PASSWORD: 'Show password',
  HIDE_PASSWORD: 'Hide password',
} as const;

export const Dashboard = {
  HI_WELCOME_BACK: 'Hi, Welcome back',
  REGISTERED_ORGANIZATIONS: 'Registered Organizations',
  TOTAL_REVENUE: 'Total Revenue',
  ORDERS_PROCESSED_TODAY: 'Orders Processed Today',
  REVENUE: 'REVENUE',
  LAST_YEAR_REVENUE: 'Last Year Revenue',
  THIS_YEAR_REVENUE: 'This Year Revenue',
  RECENT_INVOICES: 'RECENT INVOICES',
  COMPANY_NAME: 'Company Name',
  DATE: 'Date',
  AMOUNT: 'Amount',
  CHANGE_PASSWORD_TITLE: 'Change Password',
  PASSWORD_CHANGED_SUCCESS: 'Your password has been changed successfully.',
  CONFIRM_NEW_PASSWORD: 'Confirm new password',
  CHANGING_PASSWORD: 'Changing password...',
  EXPAND: 'Expand',
  PRODUCTS: 'Products',
  ORGANIZATIONS: 'Organizations',
  ORDERS: 'Orders',
  PAYMENTS: 'Payments',
  REVIEWS: 'Reviews',
  LOADING: 'Loading...',
  NO_PRODUCTS: 'No products found.',
  NO_ORGANIZATIONS: 'No organizations found.',
  NO_ORDERS: 'No orders found.',
  NO_PAYMENTS: 'No payments found.',
  NO_REVIEWS: 'No reviews found.',
  PRODUCT: 'Product',
  CATEGORY: 'Category',
  BRAND: 'Brand',
  PRICE: 'Price',
  DISCOUNT: 'Discount',
  RATING: 'Rating',
  STOCK: 'Stock',
  IN_STOCK: 'In Stock',
  LOW_STOCK: 'Low Stock',
  OUT_OF_STOCK: 'Out of Stock',
  ORGANIZATION_NAME: 'Organization Name',
  EMAIL: 'Email',
  DEPARTMENT: 'Department',
  EMPLOYEES: 'Employees',
  CITY: 'City',
  COUNTRY: 'Country',
  N_A: 'N/A',
  ORDER_NUMBER: 'Order Number',
  DESCRIPTION: 'Description',
  STATUS: 'Status',
  CUSTOMER_ID: 'Customer ID',
  TRANSACTION_ID: 'Transaction ID',
  PAYMENT_METHOD: 'Payment Method',
  USER_ID: 'User ID',
  REVIEWER: 'Reviewer',
  COMMENT: 'Comment',
  PRODUCT_ID: 'Product ID',
  LIKES: 'Likes',
} as const;

export const Errors = {
  MISSING_RESET_TOKEN: 'Missing or invalid reset token.',
  MISSING_VERIFICATION_TOKEN: 'Missing verification token.',
  INVALID_VERIFICATION_LINK: 'Invalid or expired verification link.',
  REQUEST_FAILED: 'Request failed',
  NETWORK_ERROR: 'Network error',
} as const;

export const Messages = {
  SIGNED_IN_SUCCESS: 'Signed in successfully.',
  SIGNED_OUT_SUCCESS: 'Signed out successfully.',
  ACCOUNT_CREATED_SUCCESS: 'Account created successfully.',
  RESET_INSTRUCTIONS_SENT: 'Reset instructions sent.',
  RESET_EMAIL_SENT: "If an account exists for that email, we've sent instructions to reset your password. Check your inbox.",
  PASSWORD_RESET_SUCCESS: 'Your password has been reset. You can now log in.',
  EMAIL_VERIFIED_SUCCESS: 'Email verified successfully.',
  PASSWORD_CHANGED_SUCCESS: 'Password changed successfully.',
  VERIFYING_EMAIL: 'Verifying your email...',
} as const;

export const Labels = {
  USER: 'User',
  MENU: 'menu',
  SEARCH: 'search',
  CART: 'cart',
} as const;

export const General = {
  HOME: 'Home',
} as const;
